server:
  port: 8088
spring:
  redis:
    timeout: 30000
    cluster:
      nodes:
        - 192.168.109.135:6379
        - 192.168.109.135:6380
        - 192.168.109.135:6381
      max-redirects: 3  #获取失败,最大重定向次数
    lettuce:
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
